services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./app/.env:/app/.env
    ports:
      - "8000:8000"

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

  celery:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: celery -A app worker -l INFO
    volumes:
      - ./app:/app
      - ./app/.env:/app/.env

volumes:
  postgres_data:
  redis_data:
